format = """
[╭─](fg:current_line)\
$os\
$directory\
$git_branch\
$fill\
$nodejs\
$dotnet\
$python\
$java\
$c\
$cmd_duration\
$shell\
$time\
$username\
$line_break\
$character\
"""

palette = 'dracula_plus'
add_newline = true

[palettes.dracula_plus]
foreground = '#E2E2DC'
background = '#191A21'
current_line = '#282A36'
primary = '#1A1B26'
box = '#343746'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[os]
format = '[](fg:red bg:current_line)[$symbol ](fg:background bg:red)[](fg:red)'
disabled = false

[directory]
format = '[](fg:pink bg:current_line)[󰷏 ](fg:background bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = " ~/"
truncation_symbol = ' '
truncation_length = 2
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[](fg:green bg:current_line)[$symbol](fg:background bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[nodejs]
format = '[](fg:green bg:current_line)[$symbol](fg:background bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 Node.js'

[dotnet]
format = '[](fg:purple bg:current_line)[$symbol](fg:background bg:purple)[](fg:purple bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' .NET'

[python]
format = '[](fg:green bg:current_line)[$symbol](fg:background bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' python'

[java]
format = '[](fg:red bg:current_line)[$symbol](fg:background bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Java'

[c]
format = '[](fg:blue bg:current_line)[$symbol](fg:background bg:blue)[](fg:blue bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' C'

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[](fg:orange bg:current_line)[ ](fg:background bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[shell]
format = '[](fg:blue bg:current_line)[ ](fg:background bg:blue)[](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = false

[time]
format = '[](fg:purple bg:current_line)[󰦖 ](fg:background bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[username]
format = '[](fg:yellow bg:current_line)[ ](fg:background bg:yellow)[](fg:yellow bg:box)[ $user](fg:foreground bg:box)[](fg:box) '
show_always = true

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[λ](fg:bold white)'
error_symbol = '[×](fg:bold red)'
